// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/torrent-web-seeder.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatReply_Status int32

const (
	StatReply_INITIALIZATION    StatReply_Status = 0
	StatReply_SEEDING           StatReply_Status = 1
	StatReply_IDLE              StatReply_Status = 2
	StatReply_TERMINATED        StatReply_Status = 3
	StatReply_WAITING_FOR_PEERS StatReply_Status = 4
	StatReply_RESTORING         StatReply_Status = 5
	StatReply_BACKINGUP         StatReply_Status = 6
)

// Enum value maps for StatReply_Status.
var (
	StatReply_Status_name = map[int32]string{
		0: "INITIALIZATION",
		1: "SEEDING",
		2: "IDLE",
		3: "TERMINATED",
		4: "WAITING_FOR_PEERS",
		5: "RESTORING",
		6: "BACKINGUP",
	}
	StatReply_Status_value = map[string]int32{
		"INITIALIZATION":    0,
		"SEEDING":           1,
		"IDLE":              2,
		"TERMINATED":        3,
		"WAITING_FOR_PEERS": 4,
		"RESTORING":         5,
		"BACKINGUP":         6,
	}
)

func (x StatReply_Status) Enum() *StatReply_Status {
	p := new(StatReply_Status)
	*p = x
	return p
}

func (x StatReply_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatReply_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torrent_web_seeder_proto_enumTypes[0].Descriptor()
}

func (StatReply_Status) Type() protoreflect.EnumType {
	return &file_proto_torrent_web_seeder_proto_enumTypes[0]
}

func (x StatReply_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatReply_Status.Descriptor instead.
func (StatReply_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{1, 0}
}

type Piece_Priority int32

const (
	Piece_NONE      Piece_Priority = 0
	Piece_NORMAL    Piece_Priority = 1
	Piece_HIGH      Piece_Priority = 2
	Piece_READAHEAD Piece_Priority = 3
	Piece_NEXT      Piece_Priority = 4
	Piece_NOW       Piece_Priority = 5
)

// Enum value maps for Piece_Priority.
var (
	Piece_Priority_name = map[int32]string{
		0: "NONE",
		1: "NORMAL",
		2: "HIGH",
		3: "READAHEAD",
		4: "NEXT",
		5: "NOW",
	}
	Piece_Priority_value = map[string]int32{
		"NONE":      0,
		"NORMAL":    1,
		"HIGH":      2,
		"READAHEAD": 3,
		"NEXT":      4,
		"NOW":       5,
	}
)

func (x Piece_Priority) Enum() *Piece_Priority {
	p := new(Piece_Priority)
	*p = x
	return p
}

func (x Piece_Priority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Piece_Priority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_torrent_web_seeder_proto_enumTypes[1].Descriptor()
}

func (Piece_Priority) Type() protoreflect.EnumType {
	return &file_proto_torrent_web_seeder_proto_enumTypes[1]
}

func (x Piece_Priority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Piece_Priority.Descriptor instead.
func (Piece_Priority) EnumDescriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{2, 0}
}

// Stat request message
type StatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatRequest) Reset() {
	*x = StatRequest{}
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatRequest) ProtoMessage() {}

func (x *StatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatRequest.ProtoReflect.Descriptor instead.
func (*StatRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{0}
}

func (x *StatRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Stat response message
type StatReply struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Total     int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total"`
	Completed int64                  `protobuf:"varint,2,opt,name=completed,proto3" json:"completed"`
	Peers     int32                  `protobuf:"varint,3,opt,name=peers,proto3" json:"peers"`
	Status    StatReply_Status       `protobuf:"varint,4,opt,name=status,proto3,enum=StatReply_Status" json:"status"`
	Pieces    []*Piece               `protobuf:"bytes,5,rep,name=pieces,proto3" json:"pieces"`
	Seeders   int32                  `protobuf:"varint,6,opt,name=seeders,proto3" json:"seeders"`
	Leechers  int32                  `protobuf:"varint,7,opt,name=leechers,proto3" json:"leechers"`
	// live is true when the torrent is loaded in this seeder's client and the
	// numbers above come from it; false when they were read from disk (the
	// piece-completion db) for a torrent nobody is currently streaming or
	// downloading. A cold reply has no peers by definition — the seeder did
	// not join the swarm to answer it.
	Live          bool `protobuf:"varint,8,opt,name=live,proto3" json:"live"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatReply) Reset() {
	*x = StatReply{}
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatReply) ProtoMessage() {}

func (x *StatReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatReply.ProtoReflect.Descriptor instead.
func (*StatReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{1}
}

func (x *StatReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *StatReply) GetCompleted() int64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *StatReply) GetPeers() int32 {
	if x != nil {
		return x.Peers
	}
	return 0
}

func (x *StatReply) GetStatus() StatReply_Status {
	if x != nil {
		return x.Status
	}
	return StatReply_INITIALIZATION
}

func (x *StatReply) GetPieces() []*Piece {
	if x != nil {
		return x.Pieces
	}
	return nil
}

func (x *StatReply) GetSeeders() int32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *StatReply) GetLeechers() int32 {
	if x != nil {
		return x.Leechers
	}
	return 0
}

func (x *StatReply) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

type Piece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      int64                  `protobuf:"varint,1,opt,name=position,proto3" json:"position"`
	Complete      bool                   `protobuf:"varint,2,opt,name=complete,proto3" json:"complete"`
	Priority      Piece_Priority         `protobuf:"varint,3,opt,name=priority,proto3,enum=Piece_Priority" json:"priority"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Piece) Reset() {
	*x = Piece{}
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Piece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Piece) ProtoMessage() {}

func (x *Piece) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Piece.ProtoReflect.Descriptor instead.
func (*Piece) Descriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{2}
}

func (x *Piece) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Piece) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *Piece) GetPriority() Piece_Priority {
	if x != nil {
		return x.Priority
	}
	return Piece_NONE
}

// Files requst message
type FilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesRequest) Reset() {
	*x = FilesRequest{}
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesRequest) ProtoMessage() {}

func (x *FilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesRequest.ProtoReflect.Descriptor instead.
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{3}
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Files reply message
type FilesReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilesReply) Reset() {
	*x = FilesReply{}
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesReply) ProtoMessage() {}

func (x *FilesReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_torrent_web_seeder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesReply.ProtoReflect.Descriptor instead.
func (*FilesReply) Descriptor() ([]byte, []int) {
	return file_proto_torrent_web_seeder_proto_rawDescGZIP(), []int{5}
}

func (x *FilesReply) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

var File_proto_torrent_web_seeder_proto protoreflect.FileDescriptor

const file_proto_torrent_web_seeder_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/torrent-web-seeder.proto\"!\n" +
	"\vStatRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xe4\x02\n" +
	"\tStatReply\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x1c\n" +
	"\tcompleted\x18\x02 \x01(\x03R\tcompleted\x12\x14\n" +
	"\x05peers\x18\x03 \x01(\x05R\x05peers\x12)\n" +
	"\x06status\x18\x04 \x01(\x0e2\x11.StatReply.StatusR\x06status\x12\x1e\n" +
	"\x06pieces\x18\x05 \x03(\v2\x06.PieceR\x06pieces\x12\x18\n" +
	"\aseeders\x18\x06 \x01(\x05R\aseeders\x12\x1a\n" +
	"\bleechers\x18\a \x01(\x05R\bleechers\x12\x12\n" +
	"\x04live\x18\b \x01(\bR\x04live\"x\n" +
	"\x06Status\x12\x12\n" +
	"\x0eINITIALIZATION\x10\x00\x12\v\n" +
	"\aSEEDING\x10\x01\x12\b\n" +
	"\x04IDLE\x10\x02\x12\x0e\n" +
	"\n" +
	"TERMINATED\x10\x03\x12\x15\n" +
	"\x11WAITING_FOR_PEERS\x10\x04\x12\r\n" +
	"\tRESTORING\x10\x05\x12\r\n" +
	"\tBACKINGUP\x10\x06\"\xba\x01\n" +
	"\x05Piece\x12\x1a\n" +
	"\bposition\x18\x01 \x01(\x03R\bposition\x12\x1a\n" +
	"\bcomplete\x18\x02 \x01(\bR\bcomplete\x12+\n" +
	"\bpriority\x18\x03 \x01(\x0e2\x0f.Piece.PriorityR\bpriority\"L\n" +
	"\bPriority\x12\b\n" +
	"\x04NONE\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\b\n" +
	"\x04HIGH\x10\x02\x12\r\n" +
	"\tREADAHEAD\x10\x03\x12\b\n" +
	"\x04NEXT\x10\x04\x12\a\n" +
	"\x03NOW\x10\x05\"\x0e\n" +
	"\fFilesRequest\"\x1a\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\")\n" +
	"\n" +
	"FilesReply\x12\x1b\n" +
	"\x05files\x18\x01 \x03(\v2\x05.FileR\x05files2\x89\x01\n" +
	"\x10TorrentWebSeeder\x12\"\n" +
	"\x04Stat\x12\f.StatRequest\x1a\n" +
	".StatReply\"\x00\x12*\n" +
	"\n" +
	"StatStream\x12\f.StatRequest\x1a\n" +
	".StatReply\"\x000\x01\x12%\n" +
	"\x05Files\x12\r.FilesRequest\x1a\v.FilesReply\"\x00B\x04Z\x02./b\x06proto3"

var (
	file_proto_torrent_web_seeder_proto_rawDescOnce sync.Once
	file_proto_torrent_web_seeder_proto_rawDescData []byte
)

func file_proto_torrent_web_seeder_proto_rawDescGZIP() []byte {
	file_proto_torrent_web_seeder_proto_rawDescOnce.Do(func() {
		file_proto_torrent_web_seeder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_torrent_web_seeder_proto_rawDesc), len(file_proto_torrent_web_seeder_proto_rawDesc)))
	})
	return file_proto_torrent_web_seeder_proto_rawDescData
}

var file_proto_torrent_web_seeder_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_torrent_web_seeder_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_torrent_web_seeder_proto_goTypes = []any{
	(StatReply_Status)(0), // 0: StatReply.Status
	(Piece_Priority)(0),   // 1: Piece.Priority
	(*StatRequest)(nil),   // 2: StatRequest
	(*StatReply)(nil),     // 3: StatReply
	(*Piece)(nil),         // 4: Piece
	(*FilesRequest)(nil),  // 5: FilesRequest
	(*File)(nil),          // 6: File
	(*FilesReply)(nil),    // 7: FilesReply
}
var file_proto_torrent_web_seeder_proto_depIdxs = []int32{
	0, // 0: StatReply.status:type_name -> StatReply.Status
	4, // 1: StatReply.pieces:type_name -> Piece
	1, // 2: Piece.priority:type_name -> Piece.Priority
	6, // 3: FilesReply.files:type_name -> File
	2, // 4: TorrentWebSeeder.Stat:input_type -> StatRequest
	2, // 5: TorrentWebSeeder.StatStream:input_type -> StatRequest
	5, // 6: TorrentWebSeeder.Files:input_type -> FilesRequest
	3, // 7: TorrentWebSeeder.Stat:output_type -> StatReply
	3, // 8: TorrentWebSeeder.StatStream:output_type -> StatReply
	7, // 9: TorrentWebSeeder.Files:output_type -> FilesReply
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_torrent_web_seeder_proto_init() }
func file_proto_torrent_web_seeder_proto_init() {
	if File_proto_torrent_web_seeder_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_torrent_web_seeder_proto_rawDesc), len(file_proto_torrent_web_seeder_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_torrent_web_seeder_proto_goTypes,
		DependencyIndexes: file_proto_torrent_web_seeder_proto_depIdxs,
		EnumInfos:         file_proto_torrent_web_seeder_proto_enumTypes,
		MessageInfos:      file_proto_torrent_web_seeder_proto_msgTypes,
	}.Build()
	File_proto_torrent_web_seeder_proto = out.File
	file_proto_torrent_web_seeder_proto_goTypes = nil
	file_proto_torrent_web_seeder_proto_depIdxs = nil
}
