package services

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/signal"
	"sync"
	"sync/atomic"
	"syscall"
	"time"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"

	"github.com/RoaringBitmap/roaring"
	"github.com/anacrolix/torrent"
	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"
	"github.com/webtor-io/lazymap"
	pb "github.com/webtor-io/torrent-web-seeder/proto"
)

// clientGone reports whether err is the ordinary end of a stat stream — the
// client closed the SSE connection, navigated away, or the browser tab went
// down — as opposed to a fault on our side.
//
// Worth its own helper because the distinction was previously not drawn at
// all, and the cost of that was not cosmetic: over 24h on 2026-08-15 the
// seeder logged 277 645 error records, of which 135 868 were "failed to send
// stat" and 134 471 the bare "context canceled" it turned into one frame up
// — 97% of the service's entire error signal generated by users closing
// tabs. It made the error rate a traffic counter, and a crawler wave on
// 08-14 duly read as an 85% seeder regression in the nightly report.
func clientGone(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, io.EOF) {
		return true
	}
	// gRPC wraps the peer's disappearance rather than returning the bare
	// context error, so the status code has to be checked too.
	switch status.Code(err) {
	case codes.Canceled, codes.Unavailable:
		return true
	}
	return false
}

type Stat struct {
	pb.UnimplementedTorrentWebSeederServer
	tm      *TorrentMap
	cache   lazymap.LazyMap[*pb.StatReply]
	swarms  lazymap.LazyMap[*swarmSnapshot]
	dataDir string
	// swarmReads counts readSwarm calls: the cost guards (no read with a
	// connected seeder, one read per torrent per second whatever the number
	// of paths) are invisible in the replies, so tests count.
	swarmReads atomic.Int64
}

func NewStat(tm *TorrentMap, dataDir string) *Stat {
	return &Stat{
		tm:      tm,
		dataDir: dataDir,
		cache: lazymap.New[*pb.StatReply](&lazymap.Config{
			// One second: StatStream ticks at the same pace, and the badge
			// and warm-up line in web-ui redraw from these events — three
			// seconds read as "stuck" next to a 1 s countdown. torrentStat is
			// a walk over the piece bitfield; per torrent, shared by every
			// subscriber through this cache.
			//
			// The expiry timer starts when a computation ends and a hit does
			// not touch it, while StatStream's ticker is phase-locked to its
			// first computation: the tick after a computation still hits,
			// the next one recomputes. A lone subscriber gets fresh numbers
			// every ~2 s, not every second; several subscribers or paths out
			// of phase get up to one computation a second.
			Expire:      1 * time.Second,
			StoreErrors: true,
			ErrorExpire: time.Second,
		}),
		// Per torrent, not per path: every scope asked about a torrent (a
		// season pack's episodes, the root directory) shares one read of
		// its peers a second. Filled only from statUncached, so only while
		// someone is looking.
		swarms: lazymap.New[*swarmSnapshot](&lazymap.Config{
			Expire: 1 * time.Second,
		}),
	}
}

// swarmSnapshot is what one torrent's connected peers and web seeds have,
// read at most once a second (Stat.swarms) and shared by every scope asked
// about the torrent in that second. Read-only once built.
type swarmSnapshot struct {
	// union is the union of the connected peers' piece sets,
	// torrent-indexed; nil when they were not read (webseedSeeders > 0).
	union           *roaring.Bitmap
	connected       int
	webseedSeeders  int
	partialWebseeds int
	peersFor        time.Duration
}

// readSwarm reads t's web seeds and peers through the library's public API.
// Each call below is a read lock on the client lock — one RWMutex for every
// torrent on the pod: WebseedPeerConns, Peer.Stats per web seed, PeerConns,
// and PeerConn.PeerPieces per peer, which also clones the peer's bitmap
// (Peer.newPeerPieces). So 2 + web seeds + connected peers acquisitions;
// prod runs with web seeds disabled, where it is 2 + peers. Each clone is
// folded into one union and dropped, so a snapshot holds one bitmap however
// many peers there are, and each scope's computation is O(scope), not
// O(peers × torrent). Callers skip it when a connected seeder is counted.
func readSwarm(t *torrent.Torrent, tl *peerTimeline) *swarmSnapshot {
	sw := &swarmSnapshot{peersFor: tl.connectedFor(time.Now())}
	// A web seed's piece set is readable as a count (Peer.Stats →
	// remotePieceCount of webseedPeer.peerPieces, the web seed client's
	// Pieces): every piece once the info is known (webseed.Client.SetInfo),
	// or none for a directory URL without a trailing '/', which the library
	// never requests from. The library counts it into every piece's
	// availability the same way (webseedPeer.onGotInfo), and so does this —
	// a web seed whose URL is dead claims every piece all the same, as a
	// peer's HAVE_ALL can be false.
	n := t.NumPieces()
	for _, ws := range t.WebseedPeerConns() {
		switch c := ws.Stats().RemotePieceCount; {
		case c >= n:
			sw.webseedSeeders++
		case c > 0:
			sw.partialWebseeds++
		}
	}
	if sw.webseedSeeders > 0 {
		return sw
	}
	conns := t.PeerConns()
	sw.connected = len(conns)
	sw.union = roaring.New()
	for _, pc := range conns {
		sw.union.Or(pc.PeerPieces())
	}
	return sw
}

// fillAvailability sets rep's swarm fields for the scope whose first piece is
// torrent piece offset; complete, wanted and reading are per scope piece,
// seeders is the torrent's ConnectedSeeders.
func (s *Stat) fillAvailability(rep *pb.StatReply, t *torrent.Torrent, tl *peerTimeline, seeders, offset int, complete, wanted, reading []bool) {
	in := availabilityInput{offset: offset, complete: complete, wanted: wanted, reading: reading, seeders: seeders}
	if seeders == 0 {
		sw, _ := s.swarms.Get(t.InfoHash().HexString(), func() (*swarmSnapshot, error) {
			s.swarmReads.Add(1)
			return readSwarm(t, tl), nil
		})
		in.seeders, in.connected, in.partialWebseeds, in.peersFor = sw.webseedSeeders, sw.connected, sw.partialWebseeds, sw.peersFor
		if sw.union != nil {
			in.peers = []*roaring.Bitmap{sw.union}
		}
	}
	a := computeAvailability(in)
	rep.Availability = a.fraction
	rep.AvailabilityKnown = a.known
	rep.WantedMissing = int32(a.wantedMissing)
	rep.ReaderMissing = int32(a.readerMissing)
	for _, r := range a.missing {
		rep.Missing = append(rep.Missing, &pb.PieceRange{Start: int64(r.start), End: int64(r.end)})
	}
}

func fileBytesCompleted(f *torrent.File) int64 {
	var res int64
	for _, p := range f.State() {
		if p.Complete {
			res += p.Bytes
		}
	}
	return res
}

func (s *Stat) torrentStat(t *torrent.Torrent, tl *peerTimeline) (*pb.StatReply, error) {
	completed := t.BytesCompleted()
	rStatus := pb.StatReply_SEEDING
	if completed == 0 {
		rStatus = pb.StatReply_WAITING_FOR_PEERS
	}
	numPieces := t.NumPieces()
	pieces := make([]*pb.Piece, 0, numPieces)
	complete, wanted, reading := make([]bool, numPieces), make([]bool, numPieces), make([]bool, numPieces)
	for i := 0; i < numPieces; i++ {
		p := t.Piece(i)
		ps := p.State()
		pr := pb.Piece_NONE
		if ps.Priority == torrent.PiecePriorityNormal {
			pr = pb.Piece_NORMAL
		} else if ps.Priority > torrent.PiecePriorityNormal {
			pr = pb.Piece_HIGH
		}
		pieces = append(pieces, &pb.Piece{Position: int64(i), Complete: ps.Complete, Priority: pr})
		complete[i], wanted[i], reading[i] = ps.Complete, ps.Priority > torrent.PiecePriorityNone, ps.Priority >= torrent.PiecePriorityReadahead
	}
	stats := t.Stats()
	peers := stats.ActivePeers
	seeders := stats.ConnectedSeeders
	leechers := peers - seeders
	rep := &pb.StatReply{
		Completed: completed,
		Total:     t.Info().TotalLength(),
		Peers:     int32(peers),
		Status:    rStatus,
		Seeders:   int32(seeders),
		Leechers:  int32(leechers),
		Pieces:    pieces,
		Live:      true,
	}
	s.fillAvailability(rep, t, tl, seeders, 0, complete, wanted, reading)
	return rep, nil
}

func (s *Stat) fileStat(t *torrent.Torrent, f *torrent.File, tl *peerTimeline) (*pb.StatReply, error) {
	completed := fileBytesCompleted(f)
	rStatus := pb.StatReply_SEEDING
	if completed == 0 {
		rStatus = pb.StatReply_WAITING_FOR_PEERS
	}
	state := f.State()
	pieces := make([]*pb.Piece, 0, len(state))
	complete, wanted, reading := make([]bool, len(state)), make([]bool, len(state)), make([]bool, len(state))
	for i, p := range state {
		pr := pb.Piece_NONE
		if p.Priority == torrent.PiecePriorityNormal {
			pr = pb.Piece_NORMAL
		} else if p.Priority > torrent.PiecePriorityNormal {
			pr = pb.Piece_HIGH
		}
		pieces = append(pieces, &pb.Piece{Position: int64(i), Complete: p.Complete, Priority: pr})
		complete[i], wanted[i], reading[i] = p.Complete, p.Priority > torrent.PiecePriorityNone, p.Priority >= torrent.PiecePriorityReadahead
	}
	stats := t.Stats()
	peers := stats.ActivePeers
	seeders := stats.ConnectedSeeders
	leechers := peers - seeders
	rep := &pb.StatReply{
		Completed: completed,
		Total:     f.FileInfo().Length,
		Peers:     int32(peers),
		Status:    rStatus,
		Seeders:   int32(seeders),
		Leechers:  int32(leechers),
		Pieces:    pieces,
		Live:      true,
	}
	// Position 0 is the piece the file starts in, the same piece File.State
	// starts from (offset / piece length).
	var first int
	if pl := t.Info().PieceLength; pl > 0 {
		first = int(f.Offset() / pl)
	}
	s.fillAvailability(rep, t, tl, seeders, first, complete, wanted, reading)
	return rep, nil
}

func findFile(t *torrent.Torrent, path string) *torrent.File {
	for _, f := range t.Files() {
		if samePath(f.Path(), path) {
			return f
		}
	}
	return nil
}

// isUnderDir reports whether filePath lies inside dir ("Rio (2011)" holds
// "Rio (2011)/Rio.mkv" but not "Rio (2011) extras/x.mkv").
func isUnderDir(filePath, dir string) bool {
	return len(filePath) > len(dir)+1 && filePath[:len(dir)] == dir && filePath[len(dir)] == '/'
}

// dirFiles are the torrent's files inside dir, in torrent order.
func dirFiles(t *torrent.Torrent, dir string) []*torrent.File {
	var out []*torrent.File
	for _, f := range t.Files() {
		if isUnderDir(f.Path(), dir) {
			out = append(out, f)
		}
	}
	return out
}

// dirPieceRange is the [begin, end) piece span covering the byte range
// [offset, offset+length) of a torrent with pieceLen-byte pieces.
func dirPieceRange(pieceLen, offset, length int64) (begin, end int) {
	if pieceLen <= 0 || length <= 0 {
		return 0, 0
	}
	return int(offset / pieceLen), int((offset+length-1)/pieceLen) + 1
}

// dirStat aggregates the files of a directory: bytes completed and total
// summed over them, pieces over the torrent span the directory occupies,
// positions relative to that span like fileStat's are relative to the
// file. Stats for a directory were a NotFound before (2026-09-05: ~2 000
// torrents a day answered 500 — every single-root-directory torrent whose
// resource page asked for the root item's stats), and the badge read
// "status unavailable".
func (s *Stat) dirStat(t *torrent.Torrent, files []*torrent.File, tl *peerTimeline) (*pb.StatReply, error) {
	var completed, total int64
	first, last := int64(-1), int64(0)
	for _, f := range files {
		completed += fileBytesCompleted(f)
		total += f.Length()
		if first < 0 || f.Offset() < first {
			first = f.Offset()
		}
		if end := f.Offset() + f.Length(); end > last {
			last = end
		}
	}
	rStatus := pb.StatReply_SEEDING
	if completed == 0 {
		rStatus = pb.StatReply_WAITING_FOR_PEERS
	}
	begin, end := dirPieceRange(t.Info().PieceLength, first, last-first)
	if n := t.NumPieces(); end > n {
		end = n
	}
	pieces := make([]*pb.Piece, 0, end-begin)
	complete, wanted, reading := make([]bool, end-begin), make([]bool, end-begin), make([]bool, end-begin)
	for i := begin; i < end; i++ {
		ps := t.Piece(i).State()
		pr := pb.Piece_NONE
		if ps.Priority == torrent.PiecePriorityNormal {
			pr = pb.Piece_NORMAL
		} else if ps.Priority > torrent.PiecePriorityNormal {
			pr = pb.Piece_HIGH
		}
		pieces = append(pieces, &pb.Piece{Position: int64(i - begin), Complete: ps.Complete, Priority: pr})
		complete[i-begin], wanted[i-begin], reading[i-begin] = ps.Complete, ps.Priority > torrent.PiecePriorityNone, ps.Priority >= torrent.PiecePriorityReadahead
	}
	stats := t.Stats()
	peers := stats.ActivePeers
	seeders := stats.ConnectedSeeders
	rep := &pb.StatReply{
		Completed: completed,
		Total:     total,
		Peers:     int32(peers),
		Status:    rStatus,
		Seeders:   int32(seeders),
		Leechers:  int32(peers - seeders),
		Pieces:    pieces,
		Live:      true,
	}
	s.fillAvailability(rep, t, tl, seeders, begin, complete, wanted, reading)
	return rep, nil
}

func (s *Stat) statUncached(ctx context.Context, in *pb.StatRequest) (*pb.StatReply, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return nil, errors.Errorf("No info-hash provided")
	}
	h := md.Get("info-hash")[0]
	// Look, do not touch: a torrent nobody is streaming stays unloaded and
	// its numbers come from disk (coldStat). Peek never joins the swarm or
	// extends the TTL — that is for serveFile and warm-up to do.
	t, tl := s.tm.peek(h)
	if t == nil {
		return s.coldStat(h, in.GetPath())
	}
	if in.GetPath() == "" {
		return s.torrentStat(t, tl)
	}
	f := findFile(t, in.GetPath())
	if f == nil {
		// Not a file: a directory (the resource page asks for the root
		// item, which for a single-root-directory torrent is that
		// directory) — aggregate its files. Only a path matching nothing
		// is NotFound.
		if files := dirFiles(t, in.GetPath()); len(files) > 0 {
			return s.dirStat(t, files, tl)
		}
		return nil, status.Errorf(codes.NotFound, "unable to find file for path=%v", in.GetPath())
	}
	return s.fileStat(t, f, tl)
}

func (s *Stat) Stat(ctx context.Context, in *pb.StatRequest) (*pb.StatReply, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return nil, errors.Errorf("No info-hash provided")
	}
	h := md.Get("info-hash")[0]
	key := fmt.Sprintf("%s/%s", h, in.GetPath())
	return s.cache.Get(key, func() (*pb.StatReply, error) {
		return s.statUncached(ctx, in)
	})
}

func diff(a []*pb.Piece, b []*pb.Piece) []*pb.Piece {
	var d []*pb.Piece
	for i, aa := range a {
		if i < len(b) {
			bb := b[i]
			if aa.GetComplete() == bb.GetComplete() && aa.GetPriority() == bb.GetPriority() {
				continue
			}
		}
		d = append(d, aa)
	}
	return d
}

// statChanged reports whether rep has anything a client draws that prev
// (the last reply sent; nil before the first) did not: the counters, the
// swarm split, any piece's state (diffPieces) — a priority bump, a piece now
// being fetched, used to be invisible until a piece completed — or the swarm
// availability. A torrent stuck with peers changes nothing but the last.
func statChanged(rep, prev *pb.StatReply, diffPieces []*pb.Piece) bool {
	return prev == nil ||
		rep.GetCompleted() != prev.GetCompleted() ||
		rep.GetPeers() != prev.GetPeers() ||
		rep.GetSeeders() != prev.GetSeeders() ||
		rep.GetLeechers() != prev.GetLeechers() ||
		rep.GetLive() != prev.GetLive() ||
		len(diffPieces) > 0 ||
		rep.GetAvailability() != prev.GetAvailability() ||
		rep.GetAvailabilityKnown() != prev.GetAvailabilityKnown() ||
		rep.GetWantedMissing() != prev.GetWantedMissing() ||
		rep.GetReaderMissing() != prev.GetReaderMissing() ||
		!samePieceRanges(rep.GetMissing(), prev.GetMissing())
}

func samePieceRanges(a, b []*pb.PieceRange) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i].GetStart() != b[i].GetStart() || a[i].GetEnd() != b[i].GetEnd() {
			return false
		}
	}
	return true
}

// statFrame is what StatStream sends for rep after prev (the last reply
// sent; nil before the first): pieces as the diff against it, the counters
// whole, and missing whole but only when it changed. A frame sent because
// pieces completed would otherwise repeat up to 512 unchanged ranges (~14.5
// KB against ~240 B for a one-piece diff); instead it leaves missing empty
// and sets missing_unchanged, which is false in every frame that carries
// missing — including one where it became empty — and in Stat replies.
func statFrame(rep, prev *pb.StatReply, diffPieces []*pb.Piece) *pb.StatReply {
	f := &pb.StatReply{
		Completed:         rep.GetCompleted(),
		Peers:             rep.GetPeers(),
		Seeders:           rep.GetSeeders(),
		Leechers:          rep.GetLeechers(),
		Status:            rep.GetStatus(),
		Total:             rep.GetTotal(),
		Pieces:            diffPieces,
		Live:              rep.GetLive(),
		Availability:      rep.GetAvailability(),
		AvailabilityKnown: rep.GetAvailabilityKnown(),
		WantedMissing:     rep.GetWantedMissing(),
		ReaderMissing:     rep.GetReaderMissing(),
	}
	if prev != nil && samePieceRanges(rep.GetMissing(), prev.GetMissing()) {
		f.MissingUnchanged = true
	} else {
		f.Missing = rep.GetMissing()
	}
	return f
}

// nextFrame is the frame StatStream sends for rep after prev (the last reply
// sent; nil before the first), or nil when nothing a client draws changed.
func nextFrame(rep, prev *pb.StatReply) *pb.StatReply {
	diffPieces := rep.GetPieces()
	if prev != nil {
		diffPieces = diff(rep.GetPieces(), prev.GetPieces())
	}
	if !statChanged(rep, prev, diffPieces) {
		return nil
	}
	return statFrame(rep, prev, diffPieces)
}

func (s *Stat) StatStream(in *pb.StatRequest, stream pb.TorrentWebSeeder_StatStreamServer) error {
	md, _ := metadata.FromIncomingContext(stream.Context())
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return errors.Errorf("no info-hash provided")
	}
	// No Get here: the stream must not load the torrent either. Each tick
	// goes through Stat, which peeks — cold frames while nobody streams the
	// torrent, live ones once someone does, cold again after the seeder
	// unloads it. There is no "torrent closed" event to end on any more;
	// the client closes the stream when it is done looking.
	ticker := time.NewTicker(1 * time.Second)
	// Buffered so the producer goroutine can return without a partner
	// reader (errCh) and the parent's defer can signal exit without a
	// running consumer (done). Unbuffered chans here leaked one goroutine
	// per StatStream invocation: when the parent select fired on
	// t.Closed/sigs/ctxDone before the producer had reached its select,
	// the producer parked on `errCh <- err` forever, and the parent's
	// `done <- true` blocked forever waiting for a producer that had
	// already exited via the other branch.
	errCh := make(chan error, 1)
	done := make(chan bool, 1)
	// Block the handler return on the producer goroutine's exit. Without
	// this the parent could return out of StatStream while the producer
	// was still mid-Send; net/http would finalize the response (zeroing
	// the underlying bufio.Writer) and the next Flush from the producer
	// would SIGSEGV in chunkWriter. The recover() in StatStreamServer.Send
	// is now belt-and-suspenders rather than the primary defence.
	var wg sync.WaitGroup
	wg.Add(1)
	defer func() {
		ticker.Stop()
		select {
		case done <- true:
		default:
		}
		wg.Wait()
	}()
	go func() {
		defer wg.Done()
		var prevRep *pb.StatReply
		for {
			rep, err := s.Stat(stream.Context(), in)
			if err != nil {
				// s.Stat runs on the stream's context, so a client that
				// walks away surfaces here first — not a stat failure.
				if clientGone(err) {
					log.WithField("path", in.GetPath()).Debug("client went away, stopping stats")
					errCh <- nil
					return
				}
				log.WithError(err).Error("failed to get stat")
				errCh <- err
				return
			}
			if frame := nextFrame(rep, prevRep); frame != nil {
				prevRep = rep
				if err := stream.Send(frame); err != nil {
					// Send losing the peer is the same non-event as the
					// context being cancelled — it just happens to be
					// noticed by the write rather than by the select.
					if clientGone(err) {
						log.WithField("path", in.GetPath()).Debug("client went away mid-send, stopping stats")
						errCh <- nil
						return
					}
					log.WithError(err).Error("failed to send stat")
					errCh <- err
					return
				}
				if rep.GetTotal() == rep.GetCompleted() && rep.GetStatus() != pb.StatReply_INITIALIZATION && rep.GetStatus() != pb.StatReply_RESTORING {
					errCh <- nil
					return
				}
			}
			select {
			case <-done:
				return
			case <-ticker.C:
				continue
			}
		}
	}()

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	select {
	case <-sigs:
		_ = stream.Send(&pb.StatReply{
			Status: pb.StatReply_TERMINATED,
		})
		return nil
	case <-stream.Context().Done():
		// Context.Err() is non-nil by definition once Done() has fired, so
		// the old `else` arm here — an Info "sending stats completed" — was
		// unreachable code, and the Error arm caught every ordinary
		// disconnect. This one line produced 136k of the seeder's 278k daily
		// error records.
		//
		// Returning nil rather than the context error matters as much as the
		// log level: the HTTP/SSE caller (WebSeeder.serveStats) logs whatever
		// comes back a second time and then writes an http.Error into a
		// socket the client has already closed. One non-event, two error
		// records and a doomed write.
		err := stream.Context().Err()
		if clientGone(err) {
			log.WithField("path", in.GetPath()).Debug("client went away, stopping stats")
			return nil
		}
		log.WithError(err).Error("failed to send stat")
		return err
	case <-time.After(30 * time.Minute):
		log.WithField("path", in.GetPath()).Info("sending stats timeout")
		return nil
	case err := <-errCh:
		if err != nil {
			return status.Errorf(codes.Internal, "got error=%v", err)
		}
		return nil
	}
}

func (s *Stat) Files(ctx context.Context, _ *pb.FilesRequest) (*pb.FilesReply, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return nil, errors.Errorf("no info-hash provided")
	}
	h := md.Get("info-hash")[0]
	t, err := s.tm.Get(ctx, h)
	if err != nil {
		return nil, err
	}
	var fs []*pb.File
	for _, f := range t.Files() {
		fs = append(fs, &pb.File{Path: f.Path()})
	}
	return &pb.FilesReply{Files: fs}, nil
}
