package services

import (
	"context"
	"fmt"
	"io"
	"os"
	"os/signal"
	"sync"
	"syscall"
	"time"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"

	"github.com/anacrolix/torrent"
	"github.com/pkg/errors"
	log "github.com/sirupsen/logrus"
	"github.com/webtor-io/lazymap"
	pb "github.com/webtor-io/torrent-web-seeder/proto"
)

// clientGone reports whether err is the ordinary end of a stat stream — the
// client closed the SSE connection, navigated away, or the browser tab went
// down — as opposed to a fault on our side.
//
// Worth its own helper because the distinction was previously not drawn at
// all, and the cost of that was not cosmetic: over 24h on 2026-08-15 the
// seeder logged 277 645 error records, of which 135 868 were "failed to send
// stat" and 134 471 the bare "context canceled" it turned into one frame up
// — 97% of the service's entire error signal generated by users closing
// tabs. It made the error rate a traffic counter, and a crawler wave on
// 08-14 duly read as an 85% seeder regression in the nightly report.
func clientGone(err error) bool {
	if err == nil {
		return false
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, io.EOF) {
		return true
	}
	// gRPC wraps the peer's disappearance rather than returning the bare
	// context error, so the status code has to be checked too.
	switch status.Code(err) {
	case codes.Canceled, codes.Unavailable:
		return true
	}
	return false
}

type Stat struct {
	pb.UnimplementedTorrentWebSeederServer
	tm    *TorrentMap
	cache lazymap.LazyMap[*pb.StatReply]
}

func NewStat(tm *TorrentMap) *Stat {
	return &Stat{
		tm: tm,
		cache: lazymap.New[*pb.StatReply](&lazymap.Config{
			Expire:      3 * time.Second,
			StoreErrors: true,
			ErrorExpire: time.Second,
		}),
	}
}

func fileBytesCompleted(f *torrent.File) int64 {
	var res int64
	for _, p := range f.State() {
		if p.Complete {
			res += p.Bytes
		}
	}
	return res
}

func (s *Stat) torrentStat(t *torrent.Torrent) (*pb.StatReply, error) {
	completed := t.BytesCompleted()
	rStatus := pb.StatReply_SEEDING
	if completed == 0 {
		rStatus = pb.StatReply_WAITING_FOR_PEERS
	}
	numPieces := t.NumPieces()
	pieces := make([]*pb.Piece, 0, numPieces)
	for i := 0; i < numPieces; i++ {
		p := t.Piece(i)
		ps := p.State()
		pr := pb.Piece_NONE
		if ps.Priority == torrent.PiecePriorityNormal {
			pr = pb.Piece_NORMAL
		} else if ps.Priority > torrent.PiecePriorityNormal {
			pr = pb.Piece_HIGH
		}
		pieces = append(pieces, &pb.Piece{Position: int64(i), Complete: ps.Complete, Priority: pr})
	}
	stats := t.Stats()
	peers := stats.ActivePeers
	seeders := stats.ConnectedSeeders
	leechers := peers - seeders
	return &pb.StatReply{
		Completed: completed,
		Total:     t.Info().TotalLength(),
		Peers:     int32(peers),
		Status:    rStatus,
		Seeders:   int32(seeders),
		Leechers:  int32(leechers),
		Pieces:    pieces,
	}, nil
}

func (s *Stat) fileStat(t *torrent.Torrent, f *torrent.File) (*pb.StatReply, error) {
	completed := fileBytesCompleted(f)
	rStatus := pb.StatReply_SEEDING
	if completed == 0 {
		rStatus = pb.StatReply_WAITING_FOR_PEERS
	}
	state := f.State()
	pieces := make([]*pb.Piece, 0, len(state))
	for i, p := range state {
		pr := pb.Piece_NONE
		if p.Priority == torrent.PiecePriorityNormal {
			pr = pb.Piece_NORMAL
		} else if p.Priority > torrent.PiecePriorityNormal {
			pr = pb.Piece_HIGH
		}
		pieces = append(pieces, &pb.Piece{Position: int64(i), Complete: p.Complete, Priority: pr})
	}
	stats := t.Stats()
	peers := stats.ActivePeers
	seeders := stats.ConnectedSeeders
	leechers := peers - seeders
	return &pb.StatReply{
		Completed: completed,
		Total:     f.FileInfo().Length,
		Peers:     int32(peers),
		Status:    rStatus,
		Seeders:   int32(seeders),
		Leechers:  int32(leechers),
		Pieces:    pieces,
	}, nil
}

func findFile(t *torrent.Torrent, path string) *torrent.File {
	for _, f := range t.Files() {
		if f.Path() == path {
			return f
		}
	}
	return nil
}

func (s *Stat) statUncached(ctx context.Context, in *pb.StatRequest) (*pb.StatReply, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return nil, errors.Errorf("No info-hash provided")
	}
	h := md.Get("info-hash")[0]
	t, err := s.tm.Get(ctx, h)
	if err != nil {
		return nil, err
	}
	if in.GetPath() == "" {
		return s.torrentStat(t)
	}
	f := findFile(t, in.GetPath())
	if f == nil {
		return nil, status.Errorf(codes.NotFound, "unable to find file for path=%v", in.GetPath())
	}
	return s.fileStat(t, f)
}

func (s *Stat) Stat(ctx context.Context, in *pb.StatRequest) (*pb.StatReply, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return nil, errors.Errorf("No info-hash provided")
	}
	h := md.Get("info-hash")[0]
	key := fmt.Sprintf("%s/%s", h, in.GetPath())
	return s.cache.Get(key, func() (*pb.StatReply, error) {
		return s.statUncached(ctx, in)
	})
}

func diff(a []*pb.Piece, b []*pb.Piece) []*pb.Piece {
	var d []*pb.Piece
	for i, aa := range a {
		if i < len(b) {
			bb := b[i]
			if aa.GetComplete() == bb.GetComplete() && aa.GetPriority() == bb.GetPriority() {
				continue
			}
		}
		d = append(d, aa)
	}
	return d
}

func (s *Stat) StatStream(in *pb.StatRequest, stream pb.TorrentWebSeeder_StatStreamServer) error {
	md, _ := metadata.FromIncomingContext(stream.Context())
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return errors.Errorf("no info-hash provided")
	}
	h := md.Get("info-hash")[0]
	t, err := s.tm.Get(stream.Context(), h)
	if err != nil {
		return err
	}
	ticker := time.NewTicker(3 * time.Second)
	// Buffered so the producer goroutine can return without a partner
	// reader (errCh) and the parent's defer can signal exit without a
	// running consumer (done). Unbuffered chans here leaked one goroutine
	// per StatStream invocation: when the parent select fired on
	// t.Closed/sigs/ctxDone before the producer had reached its select,
	// the producer parked on `errCh <- err` forever, and the parent's
	// `done <- true` blocked forever waiting for a producer that had
	// already exited via the other branch.
	errCh := make(chan error, 1)
	done := make(chan bool, 1)
	// Block the handler return on the producer goroutine's exit. Without
	// this the parent could return out of StatStream while the producer
	// was still mid-Send; net/http would finalize the response (zeroing
	// the underlying bufio.Writer) and the next Flush from the producer
	// would SIGSEGV in chunkWriter. The recover() in StatStreamServer.Send
	// is now belt-and-suspenders rather than the primary defence.
	var wg sync.WaitGroup
	wg.Add(1)
	defer func() {
		ticker.Stop()
		select {
		case done <- true:
		default:
		}
		wg.Wait()
	}()
	go func() {
		defer wg.Done()
		var prevRep *pb.StatReply
		for {
			rep, err := s.Stat(stream.Context(), in)
			if err != nil {
				// s.Stat runs on the stream's context, so a client that
				// walks away surfaces here first — not a stat failure.
				if clientGone(err) {
					log.WithField("path", in.GetPath()).Debug("client went away, stopping stats")
					errCh <- nil
					return
				}
				log.WithError(err).Error("failed to get stat")
				errCh <- err
				return
			}
			if prevRep == nil ||
				rep.GetCompleted() != prevRep.GetCompleted() ||
				rep.GetPeers() != prevRep.GetPeers() {
				var diffPieces []*pb.Piece
				if prevRep == nil {
					diffPieces = rep.GetPieces()
				} else {
					diffPieces = diff(rep.GetPieces(), prevRep.GetPieces())
				}
				prevRep = rep
				diffRep := &pb.StatReply{
					Completed: rep.GetCompleted(),
					Peers:     rep.GetPeers(),
					Status:    rep.GetStatus(),
					Total:     rep.GetTotal(),
					Pieces:    diffPieces,
				}
				if err := stream.Send(diffRep); err != nil {
					// Send losing the peer is the same non-event as the
					// context being cancelled — it just happens to be
					// noticed by the write rather than by the select.
					if clientGone(err) {
						log.WithField("path", in.GetPath()).Debug("client went away mid-send, stopping stats")
						errCh <- nil
						return
					}
					log.WithError(err).Error("failed to send stat")
					errCh <- err
					return
				}
				if rep.GetTotal() == rep.GetCompleted() && rep.GetStatus() != pb.StatReply_INITIALIZATION && rep.GetStatus() != pb.StatReply_RESTORING {
					errCh <- nil
					return
				}
			}
			select {
			case <-done:
				return
			case <-ticker.C:
				continue
			}
		}
	}()

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	select {
	case <-t.Closed():
		_ = stream.Send(&pb.StatReply{
			Status: pb.StatReply_TERMINATED,
		})
		return nil
	case <-sigs:
		_ = stream.Send(&pb.StatReply{
			Status: pb.StatReply_TERMINATED,
		})
		return nil
	case <-stream.Context().Done():
		// Context.Err() is non-nil by definition once Done() has fired, so
		// the old `else` arm here — an Info "sending stats completed" — was
		// unreachable code, and the Error arm caught every ordinary
		// disconnect. This one line produced 136k of the seeder's 278k daily
		// error records.
		//
		// Returning nil rather than the context error matters as much as the
		// log level: the HTTP/SSE caller (WebSeeder.serveStats) logs whatever
		// comes back a second time and then writes an http.Error into a
		// socket the client has already closed. One non-event, two error
		// records and a doomed write.
		err := stream.Context().Err()
		if clientGone(err) {
			log.WithField("path", in.GetPath()).Debug("client went away, stopping stats")
			return nil
		}
		log.WithError(err).Error("failed to send stat")
		return err
	case <-time.After(30 * time.Minute):
		log.WithField("path", in.GetPath()).Info("sending stats timeout")
		return nil
	case err := <-errCh:
		if err != nil {
			return status.Errorf(codes.Internal, "got error=%v", err)
		}
		return nil
	}
}

func (s *Stat) Files(ctx context.Context, _ *pb.FilesRequest) (*pb.FilesReply, error) {
	md, _ := metadata.FromIncomingContext(ctx)
	if len(md.Get("info-hash")) == 0 || md.Get("info-hash")[0] == "" {
		return nil, errors.Errorf("no info-hash provided")
	}
	h := md.Get("info-hash")[0]
	t, err := s.tm.Get(ctx, h)
	if err != nil {
		return nil, err
	}
	var fs []*pb.File
	for _, f := range t.Files() {
		fs = append(fs, &pb.File{Path: f.Path()})
	}
	return &pb.FilesReply{Files: fs}, nil
}
