// Code generated by protoc-gen-go. DO NOT EDIT.
// source: torrent-web-seeder.proto

package torrent_web_seeder

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatReply_Status int32

const (
	StatReply_INITIALIZATION    StatReply_Status = 0
	StatReply_SEEDING           StatReply_Status = 1
	StatReply_IDLE              StatReply_Status = 2
	StatReply_TERMINATED        StatReply_Status = 3
	StatReply_WAITING_FOR_PEERS StatReply_Status = 4
	StatReply_RESTORING         StatReply_Status = 5
	StatReply_BACKINGUP         StatReply_Status = 6
)

var StatReply_Status_name = map[int32]string{
	0: "INITIALIZATION",
	1: "SEEDING",
	2: "IDLE",
	3: "TERMINATED",
	4: "WAITING_FOR_PEERS",
	5: "RESTORING",
	6: "BACKINGUP",
}

var StatReply_Status_value = map[string]int32{
	"INITIALIZATION":    0,
	"SEEDING":           1,
	"IDLE":              2,
	"TERMINATED":        3,
	"WAITING_FOR_PEERS": 4,
	"RESTORING":         5,
	"BACKINGUP":         6,
}

func (x StatReply_Status) String() string {
	return proto.EnumName(StatReply_Status_name, int32(x))
}

func (StatReply_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{1, 0}
}

type Piece_Priority int32

const (
	Piece_NONE      Piece_Priority = 0
	Piece_NORMAL    Piece_Priority = 1
	Piece_HIGH      Piece_Priority = 2
	Piece_READAHEAD Piece_Priority = 3
	Piece_NEXT      Piece_Priority = 4
	Piece_NOW       Piece_Priority = 5
)

var Piece_Priority_name = map[int32]string{
	0: "NONE",
	1: "NORMAL",
	2: "HIGH",
	3: "READAHEAD",
	4: "NEXT",
	5: "NOW",
}

var Piece_Priority_value = map[string]int32{
	"NONE":      0,
	"NORMAL":    1,
	"HIGH":      2,
	"READAHEAD": 3,
	"NEXT":      4,
	"NOW":       5,
}

func (x Piece_Priority) String() string {
	return proto.EnumName(Piece_Priority_name, int32(x))
}

func (Piece_Priority) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{2, 0}
}

// Stat request message
type StatRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatRequest) Reset()         { *m = StatRequest{} }
func (m *StatRequest) String() string { return proto.CompactTextString(m) }
func (*StatRequest) ProtoMessage()    {}
func (*StatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{0}
}

func (m *StatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatRequest.Unmarshal(m, b)
}
func (m *StatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatRequest.Marshal(b, m, deterministic)
}
func (m *StatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatRequest.Merge(m, src)
}
func (m *StatRequest) XXX_Size() int {
	return xxx_messageInfo_StatRequest.Size(m)
}
func (m *StatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatRequest proto.InternalMessageInfo

func (m *StatRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Stat response message
type StatReply struct {
	Total                int64            `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Completed            int64            `protobuf:"varint,2,opt,name=completed,proto3" json:"completed,omitempty"`
	Peers                int32            `protobuf:"varint,3,opt,name=peers,proto3" json:"peers,omitempty"`
	Status               StatReply_Status `protobuf:"varint,4,opt,name=status,proto3,enum=StatReply_Status" json:"status,omitempty"`
	Pieces               []*Piece         `protobuf:"bytes,5,rep,name=pieces,proto3" json:"pieces,omitempty"`
	Seeders              int32            `protobuf:"varint,6,opt,name=seeders,proto3" json:"seeders,omitempty"`
	Leechers             int32            `protobuf:"varint,7,opt,name=leechers,proto3" json:"leechers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StatReply) Reset()         { *m = StatReply{} }
func (m *StatReply) String() string { return proto.CompactTextString(m) }
func (*StatReply) ProtoMessage()    {}
func (*StatReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{1}
}

func (m *StatReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatReply.Unmarshal(m, b)
}
func (m *StatReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatReply.Marshal(b, m, deterministic)
}
func (m *StatReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatReply.Merge(m, src)
}
func (m *StatReply) XXX_Size() int {
	return xxx_messageInfo_StatReply.Size(m)
}
func (m *StatReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StatReply.DiscardUnknown(m)
}

var xxx_messageInfo_StatReply proto.InternalMessageInfo

func (m *StatReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *StatReply) GetCompleted() int64 {
	if m != nil {
		return m.Completed
	}
	return 0
}

func (m *StatReply) GetPeers() int32 {
	if m != nil {
		return m.Peers
	}
	return 0
}

func (m *StatReply) GetStatus() StatReply_Status {
	if m != nil {
		return m.Status
	}
	return StatReply_INITIALIZATION
}

func (m *StatReply) GetPieces() []*Piece {
	if m != nil {
		return m.Pieces
	}
	return nil
}

func (m *StatReply) GetSeeders() int32 {
	if m != nil {
		return m.Seeders
	}
	return 0
}

func (m *StatReply) GetLeechers() int32 {
	if m != nil {
		return m.Leechers
	}
	return 0
}

type Piece struct {
	Position             int64          `protobuf:"varint,1,opt,name=position,proto3" json:"position,omitempty"`
	Complete             bool           `protobuf:"varint,2,opt,name=complete,proto3" json:"complete,omitempty"`
	Priority             Piece_Priority `protobuf:"varint,3,opt,name=priority,proto3,enum=Piece_Priority" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Piece) Reset()         { *m = Piece{} }
func (m *Piece) String() string { return proto.CompactTextString(m) }
func (*Piece) ProtoMessage()    {}
func (*Piece) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{2}
}

func (m *Piece) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Piece.Unmarshal(m, b)
}
func (m *Piece) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Piece.Marshal(b, m, deterministic)
}
func (m *Piece) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Piece.Merge(m, src)
}
func (m *Piece) XXX_Size() int {
	return xxx_messageInfo_Piece.Size(m)
}
func (m *Piece) XXX_DiscardUnknown() {
	xxx_messageInfo_Piece.DiscardUnknown(m)
}

var xxx_messageInfo_Piece proto.InternalMessageInfo

func (m *Piece) GetPosition() int64 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *Piece) GetComplete() bool {
	if m != nil {
		return m.Complete
	}
	return false
}

func (m *Piece) GetPriority() Piece_Priority {
	if m != nil {
		return m.Priority
	}
	return Piece_NONE
}

// Files requst message
type FilesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesRequest) Reset()         { *m = FilesRequest{} }
func (m *FilesRequest) String() string { return proto.CompactTextString(m) }
func (*FilesRequest) ProtoMessage()    {}
func (*FilesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{3}
}

func (m *FilesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesRequest.Unmarshal(m, b)
}
func (m *FilesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesRequest.Marshal(b, m, deterministic)
}
func (m *FilesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesRequest.Merge(m, src)
}
func (m *FilesRequest) XXX_Size() int {
	return xxx_messageInfo_FilesRequest.Size(m)
}
func (m *FilesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilesRequest proto.InternalMessageInfo

type File struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// Files reply message
type FilesReply struct {
	Files                []*File  `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilesReply) Reset()         { *m = FilesReply{} }
func (m *FilesReply) String() string { return proto.CompactTextString(m) }
func (*FilesReply) ProtoMessage()    {}
func (*FilesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_5d50c5ce2e0ede5c, []int{5}
}

func (m *FilesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilesReply.Unmarshal(m, b)
}
func (m *FilesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilesReply.Marshal(b, m, deterministic)
}
func (m *FilesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilesReply.Merge(m, src)
}
func (m *FilesReply) XXX_Size() int {
	return xxx_messageInfo_FilesReply.Size(m)
}
func (m *FilesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FilesReply.DiscardUnknown(m)
}

var xxx_messageInfo_FilesReply proto.InternalMessageInfo

func (m *FilesReply) GetFiles() []*File {
	if m != nil {
		return m.Files
	}
	return nil
}

func init() {
	proto.RegisterEnum("StatReply_Status", StatReply_Status_name, StatReply_Status_value)
	proto.RegisterEnum("Piece_Priority", Piece_Priority_name, Piece_Priority_value)
	proto.RegisterType((*StatRequest)(nil), "StatRequest")
	proto.RegisterType((*StatReply)(nil), "StatReply")
	proto.RegisterType((*Piece)(nil), "Piece")
	proto.RegisterType((*FilesRequest)(nil), "FilesRequest")
	proto.RegisterType((*File)(nil), "File")
	proto.RegisterType((*FilesReply)(nil), "FilesReply")
}

func init() { proto.RegisterFile("torrent-web-seeder.proto", fileDescriptor_5d50c5ce2e0ede5c) }

var fileDescriptor_5d50c5ce2e0ede5c = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xd1, 0x8e, 0xd2, 0x40,
	0x14, 0x86, 0x29, 0xb4, 0x05, 0x0e, 0xbb, 0x38, 0x7b, 0xa2, 0x49, 0x83, 0xc6, 0x60, 0x13, 0x13,
	0x56, 0xb3, 0x8d, 0xc1, 0x27, 0xa8, 0x32, 0x0b, 0x13, 0xd9, 0x96, 0x4c, 0x6b, 0x30, 0xde, 0x6c,
	0x80, 0x1d, 0xb3, 0x4d, 0xd8, 0x6d, 0x6d, 0x87, 0xe8, 0x3e, 0x82, 0xaf, 0xe4, 0x53, 0xf8, 0x48,
	0x66, 0x66, 0x0a, 0xec, 0x85, 0xf1, 0xae, 0xdf, 0x39, 0xff, 0x64, 0xce, 0x7f, 0xe6, 0x2f, 0x78,
	0x32, 0x2f, 0x4b, 0x71, 0x2f, 0x2f, 0x7e, 0x88, 0xf5, 0x45, 0x25, 0xc4, 0x8d, 0x28, 0x83, 0xa2,
	0xcc, 0x65, 0xee, 0xbf, 0x82, 0x5e, 0x22, 0x57, 0x92, 0x8b, 0xef, 0x3b, 0x51, 0x49, 0x44, 0xb0,
	0x8b, 0x95, 0xbc, 0xf5, 0xac, 0xa1, 0x35, 0xea, 0x72, 0xfd, 0xed, 0xff, 0x69, 0x42, 0xd7, 0x68,
	0x8a, 0xed, 0x03, 0x3e, 0x05, 0x47, 0xe6, 0x72, 0xb5, 0xd5, 0x92, 0x16, 0x37, 0x80, 0x2f, 0xa0,
	0xbb, 0xc9, 0xef, 0x8a, 0xad, 0x90, 0xe2, 0xc6, 0x6b, 0xea, 0xce, 0xb1, 0xa0, 0xce, 0x14, 0x42,
	0x94, 0x95, 0xd7, 0x1a, 0x5a, 0x23, 0x87, 0x1b, 0xc0, 0x73, 0x70, 0x2b, 0xb9, 0x92, 0xbb, 0xca,
	0xb3, 0x87, 0xd6, 0xa8, 0x3f, 0x3e, 0x0b, 0x0e, 0xb7, 0xe8, 0xaf, 0x5d, 0xc5, 0x6b, 0x01, 0xbe,
	0x04, 0xb7, 0xc8, 0xc4, 0x46, 0x54, 0x9e, 0x33, 0x6c, 0x8d, 0x7a, 0x63, 0x37, 0x58, 0x28, 0xe4,
	0x75, 0x15, 0x3d, 0x68, 0x1b, 0x57, 0x95, 0xe7, 0xea, 0x2b, 0xf6, 0x88, 0x03, 0xe8, 0x6c, 0x85,
	0xd8, 0xdc, 0xaa, 0x56, 0x5b, 0xb7, 0x0e, 0xec, 0xff, 0x04, 0xd7, 0xdc, 0x83, 0x08, 0x7d, 0x16,
	0xb1, 0x94, 0x85, 0x73, 0xf6, 0x35, 0x4c, 0x59, 0x1c, 0x91, 0x06, 0xf6, 0xa0, 0x9d, 0x50, 0x3a,
	0x61, 0xd1, 0x94, 0x58, 0xd8, 0x01, 0x9b, 0x4d, 0xe6, 0x94, 0x34, 0xb1, 0x0f, 0x90, 0x52, 0x7e,
	0xc5, 0xa2, 0x30, 0xa5, 0x13, 0xd2, 0xc2, 0x67, 0x70, 0xb6, 0x0c, 0x59, 0xca, 0xa2, 0xe9, 0xf5,
	0x65, 0xcc, 0xaf, 0x17, 0x94, 0xf2, 0x84, 0xd8, 0x78, 0x0a, 0x5d, 0x4e, 0x93, 0x34, 0xe6, 0xea,
	0xbc, 0xa3, 0xf0, 0x43, 0xf8, 0xf1, 0x13, 0x8b, 0xa6, 0x9f, 0x17, 0xc4, 0xf5, 0x7f, 0x5b, 0xe0,
	0x68, 0x07, 0x6a, 0xbe, 0x22, 0xaf, 0x32, 0x99, 0xe5, 0xf7, 0xf5, 0x46, 0x0f, 0xac, 0x7a, 0xfb,
	0x1d, 0xea, 0x9d, 0x76, 0xf8, 0x81, 0xf1, 0x2d, 0x74, 0x8a, 0x32, 0xcb, 0xcb, 0x4c, 0x3e, 0xe8,
	0xad, 0xf6, 0xc7, 0x4f, 0xcc, 0x4e, 0x82, 0x45, 0x5d, 0xe6, 0x07, 0x81, 0x3f, 0x87, 0xce, 0xbe,
	0xaa, 0x9c, 0x44, 0x71, 0x44, 0x49, 0x03, 0x01, 0xdc, 0x28, 0xe6, 0x57, 0xe1, 0xdc, 0xf8, 0x9b,
	0xb1, 0xe9, 0x8c, 0x34, 0xcd, 0xe0, 0xe1, 0x24, 0x9c, 0xd1, 0x50, 0xd9, 0x53, 0x72, 0xfa, 0x25,
	0x25, 0x36, 0xb6, 0xa1, 0x15, 0xc5, 0x4b, 0xe2, 0xf8, 0x7d, 0x38, 0xb9, 0xcc, 0xb6, 0xa2, 0xaa,
	0x33, 0xe3, 0x0f, 0xc0, 0x56, 0xfc, 0xcf, 0xec, 0x9c, 0x03, 0xd4, 0x5a, 0x95, 0x9d, 0xe7, 0xe0,
	0x7c, 0x53, 0xe4, 0x59, 0xfa, 0x15, 0x9d, 0x40, 0xf5, 0xb8, 0xa9, 0x8d, 0x7f, 0x59, 0x40, 0x52,
	0x13, 0xd3, 0xa5, 0x58, 0x27, 0xfa, 0xfd, 0xd0, 0x07, 0x5b, 0x3d, 0x11, 0x9e, 0x04, 0x8f, 0x52,
	0x3a, 0x80, 0x63, 0x52, 0xfc, 0x06, 0xbe, 0x01, 0x50, 0x98, 0xc8, 0x52, 0xac, 0xee, 0xfe, 0xa7,
	0x7c, 0x67, 0xe1, 0x6b, 0x70, 0xf4, 0x3c, 0x78, 0x1a, 0x3c, 0xf6, 0x30, 0xe8, 0x05, 0xc7, 0x31,
	0xfd, 0xc6, 0xda, 0xd5, 0x3f, 0xc7, 0xfb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x89, 0xc4,
	0x90, 0x38, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TorrentWebSeederClient is the client API for TorrentWebSeeder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TorrentWebSeederClient interface {
	// Get file stat
	Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatReply, error)
	// Get file stat stream
	StatStream(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (TorrentWebSeeder_StatStreamClient, error)
	// Get file list
	Files(ctx context.Context, in *FilesRequest, opts ...grpc.CallOption) (*FilesReply, error)
}

type torrentWebSeederClient struct {
	cc *grpc.ClientConn
}

func NewTorrentWebSeederClient(cc *grpc.ClientConn) TorrentWebSeederClient {
	return &torrentWebSeederClient{cc}
}

func (c *torrentWebSeederClient) Stat(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (*StatReply, error) {
	out := new(StatReply)
	err := c.cc.Invoke(ctx, "/TorrentWebSeeder/Stat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentWebSeederClient) StatStream(ctx context.Context, in *StatRequest, opts ...grpc.CallOption) (TorrentWebSeeder_StatStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_TorrentWebSeeder_serviceDesc.Streams[0], "/TorrentWebSeeder/StatStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &torrentWebSeederStatStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TorrentWebSeeder_StatStreamClient interface {
	Recv() (*StatReply, error)
	grpc.ClientStream
}

type torrentWebSeederStatStreamClient struct {
	grpc.ClientStream
}

func (x *torrentWebSeederStatStreamClient) Recv() (*StatReply, error) {
	m := new(StatReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *torrentWebSeederClient) Files(ctx context.Context, in *FilesRequest, opts ...grpc.CallOption) (*FilesReply, error) {
	out := new(FilesReply)
	err := c.cc.Invoke(ctx, "/TorrentWebSeeder/Files", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorrentWebSeederServer is the server API for TorrentWebSeeder service.
type TorrentWebSeederServer interface {
	// Get file stat
	Stat(context.Context, *StatRequest) (*StatReply, error)
	// Get file stat stream
	StatStream(*StatRequest, TorrentWebSeeder_StatStreamServer) error
	// Get file list
	Files(context.Context, *FilesRequest) (*FilesReply, error)
}

// UnimplementedTorrentWebSeederServer can be embedded to have forward compatible implementations.
type UnimplementedTorrentWebSeederServer struct {
}

func (*UnimplementedTorrentWebSeederServer) Stat(ctx context.Context, req *StatRequest) (*StatReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stat not implemented")
}
func (*UnimplementedTorrentWebSeederServer) StatStream(req *StatRequest, srv TorrentWebSeeder_StatStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StatStream not implemented")
}
func (*UnimplementedTorrentWebSeederServer) Files(ctx context.Context, req *FilesRequest) (*FilesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Files not implemented")
}

func RegisterTorrentWebSeederServer(s *grpc.Server, srv TorrentWebSeederServer) {
	s.RegisterService(&_TorrentWebSeeder_serviceDesc, srv)
}

func _TorrentWebSeeder_Stat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentWebSeederServer).Stat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TorrentWebSeeder/Stat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentWebSeederServer).Stat(ctx, req.(*StatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentWebSeeder_StatStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TorrentWebSeederServer).StatStream(m, &torrentWebSeederStatStreamServer{stream})
}

type TorrentWebSeeder_StatStreamServer interface {
	Send(*StatReply) error
	grpc.ServerStream
}

type torrentWebSeederStatStreamServer struct {
	grpc.ServerStream
}

func (x *torrentWebSeederStatStreamServer) Send(m *StatReply) error {
	return x.ServerStream.SendMsg(m)
}

func _TorrentWebSeeder_Files_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentWebSeederServer).Files(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TorrentWebSeeder/Files",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentWebSeederServer).Files(ctx, req.(*FilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TorrentWebSeeder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TorrentWebSeeder",
	HandlerType: (*TorrentWebSeederServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stat",
			Handler:    _TorrentWebSeeder_Stat_Handler,
		},
		{
			MethodName: "Files",
			Handler:    _TorrentWebSeeder_Files_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatStream",
			Handler:       _TorrentWebSeeder_StatStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "torrent-web-seeder.proto",
}
